[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "24"
  NEXT_TELEMETRY_DISABLED = "1"
  NX_DAEMON = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
